on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregisteryav.azurecr.io
        username: ${{ secrets.acr_containerregisteryav_username }}
        password: ${{ secrets.acr_containerregisteryav_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "DockerFile" -t containerregisteryav.azurecr.io/testcluster:${{ github.sha }}
        docker push containerregisteryav.azurecr.io/testcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testcluster92bd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testcluster92bd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testcluster92bd
        container-registry-url: containerregisteryav.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregisteryav_username }}
        container-registry-password: ${{ secrets.acr_containerregisteryav_password }}
        secret-name: testclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: testcluster92bd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerregisteryav.azurecr.io/testcluster:${{ github.sha }}
        imagepullsecrets: |
          testclusterdockerauth